---
- name: Stop and remove monitoring stack
  ansible.builtin.command:
    cmd: docker compose down -v
    chdir: "{{ monitoring_data_dir }}"
  become: true
  ignore_errors: true
  changed_when: true

- name: Remove monitoring data directory
  ansible.builtin.file:
    path: "{{ monitoring_data_dir }}"
    state: absent
  become: true
