---

- name: Enumerate all cluster HA hosts within the hosts file
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: microk8s HA Cluster Hosts"
    content: |
      {% for host in groups[microk8s_cluster] %}
      {{ hostvars[host].ip }} {{ hostvars[host].inventory_hostname }} {{ hostvars[host].inventory_hostname_short}}
      {% endfor %}

- name: Find the designated host
  set_fact:
    designated_host: '{{ (groups[microk8s_cluster]|sort)[0] }}'

- block:
  - name: Waiting for microk8s to be ready on microk8s host master
    command: "microk8s status --wait-ready"
    delegate_to: "{{ designated_host }}"
    delegate_facts: true
    changed_when: false

  - name: Get the microk8s join command from the microk8s master
    shell: "microk8s add-node | grep -E -m1 'microk8s join {{ microk8s_ip_regex_HA }}'"
    delegate_to: "{{ designated_host }}"
    delegate_facts: true
    changed_when: false
    register: microk8s_join_command

  - name: Get microk8s cluster nodes
    command: "microk8s kubectl get node"
    delegate_to: "{{ designated_host }}"
    delegate_facts: true
    changed_when: false
    register: microk8s_cluster_node

  - name: Waiting for microk8s to be ready on microk8s host node
    command: "microk8s status --wait-ready"
    changed_when: false

  - name: Set the microk8s join command on the microk8s node
    command: "{{ microk8s_join_command.stdout }}"
    when: microk8s_cluster_node.stdout.find(inventory_hostname) == -1
    register: join_command_output
    failed_when:
      - "'already known to dqlite' not in join_command_output.stdout"
      - join_command_output.rc > 0

  when:
    - inventory_hostname != designated_host
    - inventory_hostname in groups[microk8s_cluster]


