---
- name: Remove .kube folder for the user
  file:
    path: ~/.kube
    state: absent
    force: yes
  with_items: '{{ users }}'
  ignore_errors: true
  loop_control:
    loop_var: user
    label: '{{ user }}'

- name: Remove user from group
  command: "deluser {{ user }} microk8s"
  ignore_errors: true
  changed_when: true
  with_items: '{{ users }}'
  loop_control:
    loop_var: user
    label: '{{ user }}'

- name: Remove kubectl alias
  command: "snap unalias kubectl"
  ignore_errors: true

- name: Remove helm3 alias
  command: "snap unalias helm"
  ignore_errors: true

- name: Remove all cluster HA hosts from hosts file
  blockinfile:
    dest: /etc/hosts
    marker: "# {mark} ANSIBLE MANAGED: microk8s HA Cluster Hosts"
    state: absent
    content: |
      {% for host in groups[microk8s_cluster] %}
      {{ hostvars[host].ansible_default_ipv4.address }} {{ hostvars[host].ansible_hostname }}
      {% endfor %}

- name: Find the designated host
  set_fact:
    designated_host: '{{ (groups[microk8s_cluster]|sort)[0] }}'

- name: Remove worker nodes microk8 via snap
  snap:
    name: microk8s
    state: absent
  ignore_errors: true
  when:
    - inventory_hostname != designated_host

- name: Remove master nodes microk8 via snap
  snap:
    name: microk8s
    state: absent
  ignore_errors: true
  when:
    - inventory_hostname == designated_host

