---
- name: Find the designated host
  set_fact:
    designated_host: '{{ (groups[microk8s_cluster]|sort)[0] }}'

- name: Setup Redis via the designated host
  import_tasks: setup.yml
  when:
    - not reset | bool
    - inventory_hostname == designated_host

- name: Reset Redis via the designated host
  include_tasks: reset.yml
  when:
    - reset | bool
    - inventory_hostname == designated_host
