---
reset: False
microk8s_disable_snap_autoupdate: false

#microk8s_version: 1.32
microk8s_channel: 1.32

# users to make members of microk8s group
users: [jefcox]

# regex to select IP address for joining nodes in HA setup
microk8s_ip_regex_HA: "([0-9]{1,3}[\\.]){3}[0-9]{1,3}"

#dns addon dns resolver
microk8s_dns_resolvers: 10.220.1.1

#metallb addon ip pool
microk8s_lb_pool: 10.220.1.201-10.220.1.245

helm3_repositories:
  - name: stable
    url: https://charts.helm.sh/stable

microk8s_csr_template: "csr.conf.template.j2"

