---
- name: Install base dependencies
  ansible.builtin.apt:
    name: '{{ base_dependencies }}'
    state: present
    autoremove: true
    update_cache: yes

- name: Ensure apt version of python kubernetes is not installed
  ansible.builtin.apt:
    name: python3-kubernetes
    state: absent
    update_cache: yes


- name: Install python kubernetes
  ansible.builtin.pip:
    break_system_packages: true
    name: kubernetes

- name: Install linux headers
  ansible.builtin.apt:
    name: linux-headers-{{ ansible_kernel }}
    state: present
    autoremove: true
    update_cache: yes


- name: Set route metric
  command:
    cmd: "netplan set ethernets.{{ hostvars[inventory_hostname].interface}}.dhcp4-overrides.route-metric=50"
  notify:
    - Apply netplan

