---
- name: Install base dependencies
  ansible.builtin.apt:
    name: '{{ base_dependencies }}'
    state: present
    update_cache: yes

- name: Install kubernetes python library
  ansible.builtin.pip:
    name: kubernetes
    state: present
  become_user: "{{ ansible_env.SUDO_USER }}"  # Install as non root user!

- name: Set route metric
  command:
    cmd: "netplan set ethernets.{{ hostvars[inventory_hostname].interface}}.dhcp4-overrides.route-metric=50"
  notify:
    - Apply netplan

- name: Start iscsi
  command:
    cmd: systemctl enable --now iscsid

