---

- name: Remove linux headers
  ansible.builtin.apt:
    name: linux-headers-{{ ansible_kernel }}
    state: absent
    update_cache: yes

- name: Remove base dependencies
  ansible.builtin.apt:
    name: '{{ base_dependencies }}'
    state: absent
    update_cache: yes


