---
# r720xd — 2x E5-2620, 94G RAM, 24 vCPUs
# Boot: sda (2.7T SAS, PVE)
# Ceph-Bulk 1.8T SAS: sdb, sdc, sde, sdf, sdh, sdi (6x 1.8T) → hdd class
# Ceph-Bulk 2.7T SAS: sdd, sdg, sdj, sdk, sdl (5x 2.7T) → hdd class
# Ceph NIC: nic5 (QLogic qede, requires forced 10G speed)

ceph_nic: "nic5"
ceph_ip: "10.220.2.10"

ceph_disks:
  - name: sdb
    device_class: hdd
  - name: sdc
    device_class: hdd
  - name: sdd
    device_class: hdd
  - name: sde
    device_class: hdd
  - name: sdf
    device_class: hdd
  - name: sdg
    device_class: hdd
  - name: sdh
    device_class: hdd
  - name: sdi
    device_class: hdd
  - name: sdj
    device_class: hdd
  - name: sdk
    device_class: hdd
  - name: sdl
    device_class: hdd
