---
- name: Ensure zfsutils-linux is installed
  ansible.builtin.apt:
    name: zfsutils-linux
    state: present
    autoremove: true
    update_cache: yes

- name: Check if ZFS Pool Exists
  ansible.builtin.command: zpool list {{ item.name }}
  register: zpool_check
  ignore_errors: yes
  no_log: true
  with_items: "{{ zfs_pools | default([]) }}"

- name: Create ZFS pool if it does not exist
  ansible.builtin.command: zpool create {{ item.name }} {{ item.mode }} {{ item.devices | join(' ') }} {{ item.options }}
  when: zpool_check.results[item_index].rc != 0
  with_items: "{{ zfs_pools | default([]) }}"
  loop_control:
    index_var: item_index

