---

- name: Find the designated host
  set_fact:
    designated_host: '{{ (groups[microk8s_cluster]|sort)[0] }}'

- name: Found designated host
  debug:
    msg: Designated host ==> {{ designated_host }}

- name: Waiting for microk8s to be ready on microk8s host master
  command: "microk8s status --wait-ready"
  delegate_to: "{{ designated_host }}"
  delegate_facts: true
  changed_when: false

- name: Setup kubernetes API
  import_tasks: setup.yml
  when: not reset | bool

- name: Reset kubernetes API
  include_tasks: reset.yml
  when: reset | bool
