---
reset: False

# letsencrypt email for cert-manager
letsencrypt_email: "namredips@gmail.com"

#dns addon dns resolver
microk8s_dns_resolvers: 10.220.1.1

#metallb addon ip pool
microk8s_lb_pool: 10.220.1.201-10.220.1.245

microk8s_addons:
  community: true                         # Enables the community addons repository
  dns: "{{ microk8s_dns_resolvers }}"     # CoreDNS
  ha-cluster: true                        # Allows for high availability on clusters with at least three nodes.
  helm: true                              # Helm 2 - the package manager for Kubernetes
  helm3: true                             # Helm 3 - Kubernetes package manager
  host-access: true                       # Allow Pods connecting to Host services smoothly
  ingress: true                           # Ingress controller for external access
  metallb: "{{ microk8s_lb_pool }}"       # Loadbalancer for your Kubernetes cluster
  metrics-server: true                    # K8s Metrics Server for API access to service metrics
  rbac: true                              # Role-Based Access Control for authorisation
  cert-manager: true                      # Cert-Manager for managing TLS certificates
