---

- name: Refresh certs 
  loop:
    - microk8s.refresh-certs --cert server.crt
    - microk8s.refresh-certs --cert front-proxy-client.crt 
    - microk8s.refresh-certs --cert ca.crt
  loop_control:
    label: "{{ item }}"
  command:
    cmd: "{{ item }}"


