---
- name: Create a external-dns kubernetes namespace
  become_user: "{{ kube_admin_user }}"
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ external_dns_namespace }}"
    state: present

- name: Setup external-dns helm repo
  become_user: "{{ kube_admin_user }}"
  kubernetes.core.helm_repository:
    name: external-dns
    repo_url: https://kubernetes-sigs.github.io/external-dns/
    state: present

- name: Create external-dns-unifi-secret kubernetes secret
  become_user: "{{ kube_admin_user }}"
  kubernetes.core.k8s:
    api_version: v1
    kind: Secret
    name: external-dns-unifi-secret
    namespace: "{{ external_dns_namespace }}"
    state: present
    definition:
      metadata:
        name: "{{ unifi_secret_key }}"
        namespace: "{{ external_dns_namespace }}" 
      type: Opaque
      data:
        username: "{{ unifi_username | b64encode }}"
        password: "{{ unifi_password | b64encode }}"

- name: Install External-dns-unifi Helm chart
  become_user: "{{ kube_admin_user }}"
  kubernetes.core.helm:
    name: external-dns-unifi
    chart_ref: external-dns/external-dns
    release_namespace: "{{ external_dns_namespace }}"
    update_repo_cache: true
    wait: true
    values:
      fullnameOverride: external-dns-unifi
      logLevel: &logLevel debug
      provider:
        name: webhook
        webhook:
          image:
            repository: ghcr.io/kashalls/external-dns-unifi-webhook
            tag: "{{ external_dns_chart_version }}"
          env:
            - name: UNIFI_HOST
              value: "{{ unifi_host }}"
            - name: UNIFI_EXTERNAL_CONTROLLER
              value: "{{ unifi_external_controller }}"
            - name: UNIFI_USER
              valueFrom:
                secretKeyRef:
                  name: "{{ unifi_secret_key }}"
                  key: username
            - name: UNIFI_PASS
              valueFrom:
                secretKeyRef:
                  name: "{{ unifi_secret_key }}"
                  key: password
            - name: LOG_LEVEL
              value: *logLevel
          livenessProbe:
            httpGet:
              path: /healthz
              port: http-webhook
            initialDelaySeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: http-webhook
            initialDelaySeconds: 10
            timeoutSeconds: 5
      extraArgs:
        - --ignore-ingress-tls-spec
      policy: sync
      sources: "{{ external_dns_sources }}"
      txtOwnerId: "{{ external_dns_txt_owner_id }}"
      txtPrefix: "{{ external_dns_txt_prefix }}"
      domainFilters: "{{ external_dns_domain_filters }}"

