---
- hosts: master
  gather_facts: yes
  become_user: "{{ kube_admin_user }}"
  roles:
    - { role: kubernetes, reset: True, tags: [ 'api' ]}
    - { role: kubernetes_dashboard, reset: True, tags: [ 'dashboard' ]}
    - { role: mayastor, reset: True, tags: [ 'mayastor' ]}
