---

- name: Add nodeport to kubernetes
  become_user: "{{ kube_admin_user }}"
  k8s:
    verify_ssl: no
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: kubernetes
        namespace: default
      spec:
        type: NodePort
        ports:
        - nodePort: 30443
          port: 443
          protocol: TCP
          targetPort: 16443

