---

- name: Reset api to ClusterIP
  become_user: "{{ kube_admin_user }}"
  k8s:
    verify_ssl: no
    definition:
      apiVersion: v1
      kind: service
      metadata:
        name: kubernetes
        namespace: default
      spec:
        type: ClusterIP
        ports:
        - name: https
          port: 443
          protocol: TCP
          targetPort: 16443
